#!/goinfre/preina-g/miniconda3/envs/42AI-preina-g/bin/python3.7
# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    scorpion.py                                        :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: preina-g <preina-g@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/04/18 23:34:07 by preina-g          #+#    #+#              #
#    Updated: 2023/04/18 23:34:07 by preina-g         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

import exifread
import os
import sys


def scorpion(path):
    try:
        print("\n\nFROM:", path, '\n')
        with open(path, 'rb') as file:
            metadates = exifread.process_file(file)
            for key in metadates.keys():
                print('IMAGE DATA: {} -> {}'.format(key, metadates[key]))
    except FileNotFoundError:
        print('ERROR: Wrong format or inexistent file\nOnly support .jpg/.jpeg .png .gif .bmp  ->', path)
        return
    
if __name__=='__main__':
    args = sys.argv[1:]
    for d in args:
        if d.endswith('.jpeg') or d.endswith('.png') or d.endswith('.gif') or d.endswith('.jpg') or d.endswith('.bmp'):
            scorpion(d)
        else:
            print('ERROR: Wrong format or inexistent file\nOnly support .jpg/.jpeg .png .gif .bmp  ->', d)